### ISSUE TITLE
"unknown opcode"

### ISSUE THREAD

**Issue by tfuuuu** [ojii/django-multilingual-ng#11]
suddenly i got this error when saving multilingual models now. and in templates when trying to render queries from this models

also i got these messages in console (development server):

XXX lineno: 1197, opcode: 44
XXX lineno: 1197, opcode: 44
XXX lineno: 1197, opcode: 44

**Comment by ojii** [comment]
does it really say XXX or is there a file name? This does not look like a django-multilingual-ng specific issue.
