### ISSUE TITLE
Admin not saving in chosen language

### ISSUE THREAD

**Issue by diogobaeder** [ojii/django-multilingual-ng#12]
Hi, there,

I've configured a website to run under "en" and "pt-br", but only content for "en" is being saved. When I try to save "pt-br" content, it gives me a success message, but the data is not saved.

Any ideas?

**Comment by diogobaeder** [comment]
The issue is affecting multilingual flatpages.

**Comment by ojii** [comment]
what revision of django-multilingual-ng are you using? What version of django are you using? Could you please show me the admin/models code you use?

**Comment by diogobaeder** [comment]
Hi, ojii, I'm using the latest commit from django-multilingual-ng and updated django trunk, both as of yesterday (when I posted this issue). Only after I raised this issue I noticed a message somewhere saying ng is not working with django, and will only be fixed when they release a stable version, is it right?

**Comment by ojii** [comment]
indeed that is the case, please try applying this [patch](http://wiki.github.com/ojii/django-multilingual-ng/patch-to-get-django-multilingual-ng-to-work-with-django-trunk) to query.py and see if this issue still persists.

**Comment by diogobaeder** [comment]
Yay!!! Problem solved!!! Thanks a lot, ojii!!! :-)
I believe this patch was not applied to master because backwards compatibility with Django 1.1, right?

**Comment by ojii** [comment]
wrong, django-multilingual-ng will NOT be 1.1 compatible. The reason for this patch not being applied yet is that there's no official package of Django 1.2 yet which requires this patch. Beta 1 works without (and will break with it). The patch will be applied as soon as the next release (probably rc1) hits.
