### ISSUE TITLE
Prepopulated_fields (slugs) not supported by django-multilingual-ng in admin panel.

### ISSUE THREAD

**Issue by meme-zz** [ojii/django-multilingual-ng#15]
--- edit --- :

My mistake, I should use use_prepopulated_fields

Is there any documentation?

Thanks,
regards.

**Comment by ojii** [comment]
The documentation is a big open issue. The best way to improve it is to write up some and send me a pull request

**Comment by meme-zz** [comment]
I think that the best way to do it is write some examples..

**Comment by Natim** [comment]
Here is a simple example :

```
from multilingual.admin import MultilingualModelAdmin

class PageAdmin(MultilingualModelAdmin):
    use_prepopulated_fields = {'slug': ('title',)}

admin.site.register(Page, PageAdmin)
```
