### ISSUE TITLE
prepopulated_fields inside translation

### ISSUE THREAD

**Issue by aronchi** [ojii/django-multilingual-ng#19]
I need both "slug" and "name" fields to be translated.

I've tried to put prepopulated_fields inside admin.py but it doesn't work.

django-multilingual seems to solve this problem with this solution:
http://code.google.com/p/django-multilingual/issues/detail?id=23&can=1&q=prepopulated_fields#c9

but it doesn't work for django-multilingual-ng

Any hint? Thanks in advance

**Comment by meme-zz** [comment]
You should use "use_prepopulated_fields" attr.

  use_prepopulated_fields = {'slug': ('name',)}

regards.
