### ISSUE TITLE
use_fieldsets and use_prepopulated_fields

### ISSUE THREAD

**Issue by nesh** [ojii/django-multilingual-ng#2]
> I'll write documentation once this project hits a somewhat stable level.

I know that is too early for documentation but it will be nice to at least mention using `use_fieldsets` and `use_prepopulated_fields` instead originals. It will save others digging through source to find how to add fieldsets and prepopulated fields to admin.

**Comment by ojii** [comment]
well in most cases the "old" multilingual docs apply. Unfortunately i'm way too busy at the moment to write any docs, however I hope to find some time next week.

**Comment by nesh** [comment]
AFAIK their doc don't mention that too (and their flatpage implementation is identical to yours). Not a big problem anyway.
