### ISSUE TITLE
"cannot import name connections" with Django 1.1.1

### ISSUE THREAD

**Issue by rekognize** [ojii/django-multilingual-ng#20]
I am getting "cannot import name connections" exception while trying to use django-multilingual-ng 0.1.20 with Django 1.1.1. 

The exception comes from the line 15 of query.py where it tries to do:

```
from django.db import connections, DEFAULT_DB_ALIAS 
```

Is it not compatible with Django 1.1.1?

Thanks,
oMat

**Comment by ojii** [comment]
django-multilingual-ng is NOT compatible with django 1.1.1 (see README). It requires 1.2 rc 1 or higher
