### ISSUE TITLE
__unicode__ method not working

### ISSUE THREAD

**Issue by diogobaeder** [ojii/django-multilingual-ng#21]
Hi there,

If I define the **unicode** method on a translated model, I get the following error:
http://dpaste.com/193544/

It only comes back to work if I comment out the method definition (thus displaying the model listing by showing the object IDs).

Any ideas?

Thanks!

**Comment by diogobaeder** [comment]
Oops, never mind, it was a missing title for one of the languages... sorry!

**Comment by ojii** [comment]
never use a ml field directly in **unicode**! Always check if it's actually filled before you return something and provide a fallback

**Comment by diogobaeder** [comment]
Thanks a lot for the tip, Ojii! I'll keep an eye at it! :-)
