### ISSUE TITLE
Inheritance don't work

### ISSUE THREAD

**Issue by nesh** [ojii/django-multilingual-ng#3]
Mixing translations with inheritance don't work at this moment, is there any work done in that direction or at least some pointers?

**Comment by ojii** [comment]
Could you provide a use case on what you try to do, what you expect to happen and what actually happens?

**Comment by nesh** [comment]
You can check inheritance branch of my fork - I added there some test cases.

I plan to look into it during the weekend and see if I can make it work.

**Comment by ojii** [comment]
Since ojii@0660482930b5c575ceaa4f9335a6c87ead68220c you can define a 'related_name' on the Translation model's Meta class.
