### ISSUE TITLE
Define fieldset in Admin

### ISSUE THREAD

**Issue by Natim** [ojii/django-multilingual-ng#30]
The field are ordered randomly in the AdminForm and when we want to define the `fieldset` of the `MultilingualModelAdmin` it says that all the field in class Translation are missing from the form.

How can I change the order of my fields ?

**Comment by ojii** [comment]
you have to use the `use_fieldset` property. It's the same as `fieldset` but works with multilingual models.

**Comment by Natim** [comment]
Ok thanks can you just add a FAQ to the WIKI with all this answer, it could be very useful ?

Thanks a lot for your help.

**Comment by ojii** [comment]
I'll write proper documentation once I get to it.
