### ISSUE TITLE
csrf missing in flatpages 

### ISSUE THREAD

**Issue by k1000** [ojii/django-multilingual-ng#33]
in flatpages/view.py

FIX
needs import:
"from django.views.decorators.csrf import csrf_protect"

and decorate "multilingual_flatpage" view with "@csrf_protect"

**Comment by ojii** [comment]
other fix is to use the csrf middlewares. if anything happens to the flatpages app in mlng, it'll be deleted.

**Comment by k1000** [comment]
it's a way how it work in original flatpages in the latest trunk. So I think its expected solution.

**Comment by ojii** [comment]
yes but flatpages in MLNG is just another thing I have to maintain that does not really serve a core purpose.

**Comment by k1000** [comment]
anyway thank you for sharing :)
