### ISSUE TITLE
flatpages still doesn't work

### ISSUE THREAD

**Issue by tfuuuu** [ojii/django-multilingual-ng#4]
> I didn't touch flatpages or tested it since i have no use for it. that 'strange error' 
> is due to a hidden field not being filled in. 

this fields actually can't be filled. i don't able to fill "title" and "content" fields

upgraded for new version. still doesn't work

> did you at least 'convert' it to the new multilingual (using manage.py mlng_convert)?

nope. i drop all tables and trying to plug multilingual-ng from scratch

**Comment by tfuuuu** [comment]
and also here is mistake in last commit (in flatpages/admin.py)

> import multilingual.admin import MultilingualModelAdmin, MultilingualModelAdminForm

but correcting this didn't help anyway

**Comment by nesh** [comment]
here is a temporary fix:
http://github.com/nesh/django-multilingual-ng/commit/24eb0fc0e568ced7ae1514b8ee9b9949b4bc6880

**Comment by ojii** [comment]
merged that commit

**Comment by ojii** [comment]
is this still an issue? I'm actually considering dropping flatpages (since I don't really see a point for them..)

**Comment by nesh** [comment]
Not a problem for me, it's not a big problem rolling custom flatpages implementation when needed.

**Comment by tfuuuu** [comment]
this is not an issue anymore. all works fine.
i don't know why you want to drop it. it's not a big problem rolling any implementation when needed, but this is already done and works well

**Comment by ojii** [comment]
i won't drop it. I was thinking about that because I thought I'll only have troubles with it. But it turns out it's actually a quite nice thing to have to test stuff.
