### ISSUE TITLE
The GLLError (Global Language Lock is not active) when adding a multilinugual inline

### ISSUE THREAD

**Issue by piotrkilczuk** [ojii/django-multilingual-ng#43]
Traceback: https://gist.github.com/716560

Adding following to admin ends in 'The Global Language Lock is not active' raised.

Admin code: https://gist.github.com/716549

Model code: https://gist.github.com/716556

**Comment by adamkal** [comment]
Hi,
I've been looking at this error but I cant reproduce it. I used your code but substituted your slug field with normal slug field and i've used the normal storage

**Comment by piotrkilczuk** [comment]
Yepp, bug in code in my fork. Closing.
