### ISSUE TITLE
Addition translation in admin

### ISSUE THREAD

**Issue by vasylnakvasiuk** [ojii/django-multilingual-ng#8]
For example:
When I have models with 3 lang, in admin I add translation for one lang and save... But no error was appeared. I think, if fields in model are required - translation must be required too.
And, if I add translation for only one lang - changing translation in my site doesn't work.

**Comment by vasylnakvasiuk** [comment]
When I add translation - I must restart server... Otherwise, changing lang (POST method) doesn't work.

**Comment by ojii** [comment]
Hi vaxXxa

I am afraid I do not understand the issue you have. Could you please provide me with the code you use that generates this issue? Also please tell me your Django version and django-multilingual-ng revision.

**Comment by vasylnakvasiuk** [comment]
I use:
Django 1.2 alpha
Python 2.6.4
ojii-django-multilingual-ng-3efca42

class NewsPost(models.Model):
    author = models.ForeignKey(User, verbose_name=_('Автор'), related_name='newsposts')
    class Translation(multilingual.Translation):
        title = models.CharField(_('Заглавие'), max_length=150)
        body = models.TextField(_('Текст'))
    timestamp = models.DateTimeField(_('Дата'))
    comment = models.TextField(_('Примечание'), blank=True)

1) WHen I try to add first instance of NewsPost's models by admin page, the first problem is ---> language: None
2) Then I enter data and  click "Save". New NewsPost's object has been saved, but if I open again this object - there are no data, but I can see normal lang ---> language: en, uk, ru... (because, data entered to "language: None")
3) I think, if fields in model are required - translation must be required too.
So, I don't understand. If I entered data only in one lang tab (for example "en"), and save. And, after that change in my site lang to "ru". But there no any data!!!! So, translation must be required.

**Comment by ojii** [comment]
please use the lastest revision of django-multilingual-ng, that bug has been fixed.

**Comment by vasylnakvasiuk** [comment]
really!)))
sorry) thnx)

**Comment by ojii** [comment]
no worries, thanks for reporting it
